---
name: Build release image

"on":
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-release-image.yml
    branches:
      - main

jobs:
  build-release-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        release:
          - "318.6"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: git clone --depth 1 --branch ${{ matrix.release }} https://github.com/gardenlinux/gardenlinux.git
      - run: make openstack BUILDKEY=info@23technologies.cloud
        working-directory: gardenlinux
      - run: mkdir gardenlinux/.build/openstack/upload
      - run: qemu-img convert -f raw -O qcow2 $(date +'%Y%m%d')/amd64/bullseye/rootfs.raw upload/gardenlinux-amd64.${{ matrix.release }}.qcow2
        working-directory: gardenlinux/.build/openstack
