---
name: Build release image

"on":
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-release-image.yml
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-release-image.yml

jobs:
  build-release-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        release:
          - "318.6"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: git clone --depth 1 --branch ${{ matrix.release }} https://github.com/gardenlinux/gardenlinux.git
      - name: Build image
        shell: 'script -q -e -c "bash {0}"'
        run: make openstack BUILDKEY=info@23technologies.cloud
        working-directory: gardenlinux
      - run: mkdir gardenlinux/.build/openstack/upload
      - run: sudo apt-get install -y qemu-utils
      - run: qemu-img convert -f raw -O qcow2 $(ls -1 | head -n 1)/amd64/bullseye/rootfs.raw upload/gardenlinux-amd64.${{ matrix.release }}.qcow2
        working-directory: gardenlinux/.build/openstack
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          SOURCE_DIR: gardenlinux/.build/openstack/upload
        if: github.ref == 'refs/heads/main'
