---
name: Build branch image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - .github/workflows/build-branch-image.yml
    branches:
      - main

jobs:
  build-branch-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch:
          - main

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: git clone --depth 1 --branch ${{ matrix.branch }} https://github.com/gardenlinux/gardenlinux.git
      - run: make openstack BUILDKEY=info@23technologies.cloud
        working-directory: gardenlinux
      - run: mkdir gardenlinux/.build/openstack/upload
      - run: qemu-img convert -f raw -O qcow2 $(date +'%Y%m%d')/amd64/bullseye/rootfs.raw upload/gardenlinux-amd64.${{ matrix.branch }}.qcow2
        working-directory: gardenlinux/.build/openstack
